spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  http:
    encoding:
      charset: UTF-8
      force: true

server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xjh.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
